export const BUSINESS_NAME = 'Shapewear Closet'
export const TAGLINE = 'Confidence starts from underneath'
export const PHONE = '233242711007'
export const EMAIL = 'Shapewearcloset3@gmail.com'
export const LOCATION = 'Ashongman Estate, Accra'
export const TIKTOK = 'https://www.tiktok.com/@shapewear_closet'
